### PR TITLE
Change of error

### PR DESCRIPTION
**Pull request by Sarita-Singh**
Change of error #8 
Added red background with error wriiten with white foreground. Removed the text "----------|| BUCKSHOT++ ||----------".

### CODE REVIEW

**Comment by MoskalykA** [comment]
Can you post a picture of the result?

**Comment by Sarita-Singh** [comment]
Hey, the error will now be shown against red console background like shown below.
bucksorterror

**Comment by MoskalykA** [comment]
Closes: #8

**Comment by MoskalykA** [comment]
Thanks <3

**Pull request merged**
